// auth
export const AUTH_START = 'AUTH_START';

export const REGISTER_USER = 'REGISTER_USER';
export const lOGIN_USER = 'lOGIN_USER';

export const AUTH_FAILED = 'AUTH_FAILED';
export const LOGOUT_USER = 'LOGOUT_USER';

export const SET_USER_INFO = 'SET_USER_INFO';
// project
export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS';
export const ADD_PROJECT_FAILED = 'ADD_PROJECT_FAILED';

export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const GET_PROJECTS_FAILED = 'GET_PROJECTS_FAILED';

export const CLEAR_PROJECT = 'CLEAR_PROJECT';

export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
export const GET_TASKS_FAILED = 'GET_TASKS_FAILED';
export const UPDATE_TASK_FAILED = 'UPDATE_TASK_FAILED';
export const CLEAR_TASKS = 'CLEAR_TASKS';
// reset
export const RESET_ALL = 'RESET_ALL';
